# Generated by Django 5.1.4 on 2024-12-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="profile",
        ),
    ]
